name: jmeter-storm-deployment

releases:
- name: jmeter-tornado
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: workers
  instances: 3
  vm_type: REPLACE_ME
  stemcell: trusty
  azs: [z1]
  networks:
  - name: REPLACE_ME
  jobs:
  - name: jmeter_storm_worker
    release:  jmeter-tornado
    properties: {}

- name: storm
  instances: 1
  lifecycle: errand
  vm_type: REPLACE_ME
  stemcell: trusty
  azs: [z1]
  networks:
  - name: REPLACE_ME
  jobs:
  - name: jmeter_storm
    release:  jmeter-tornado
    properties:
      wizard:
        configuration:
          users: 100
          ramp_time: 30
          duration: 300
        targets:
        - name: POST with Headers and Body
          url: "http://api.example.com:8080/greeting/post/"
          http_method: POST
          headers:
          - name: "Authorization"
            value: "Basic Y2F0Om1lb3c="
          options:
            request_body: |
              {"name" : "i am a post", "age" : 425}

update:
  canaries: 5
  max_in_flight: 5
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
