name: jmeter-storm-deployment

director_uuid: REPLACE_ME

releases:
- name: jmeter-tornado
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: jmeter_workers
  instances: 3
  vm_type: REPLACE_ME
  stemcell: trusty
  azs: [z1]
  networks:
  - name: REPLACE_ME
  jobs:
  - name: jmeter_worker

- name: storm
  instances: 1
  lifecycle: errand
  vm_type: REPLACE_ME
  stemcell: trusty
  azs: [z1]
  networks:
  - name: REPLACE_ME
  jobs:
  - name: jmeter_storm
    properties:
      generate_dashboard: true
      test_plan_xml: |
        {Your jmeter JMX plan goes here}

update:
  canaries: 5
  max_in_flight: 5
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
