name: jmeter-tornado-deployment

releases:
- name: jmeter-tornado
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: jmeter_attackers
  instances: 3
  vm_type: REPLACE_ME
  stemcell: trusty
  azs: [z1]
  networks:
  - name: REPLACE_ME
  jobs:
  - name: jmeter_tornado
    release: jmeter-tornado
    properties:
      wizard:
        configuration:
          users: 50
          ramp_time: 30
        targets:
        - name: GET with Headers
          url: "http://api.example.com:8080/greeting/get/"
          http_method: GET
          headers:
          - name: "Authorization"
            value: "Basic Y2F0Om1lb3c="

update:
  canaries: 5
  max_in_flight: 5
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
